load_data:
  sep: ','
  train_data:
    path: "data/data_train.csv"
  test_data:
    path: "data/data_test.csv"

select_columns:
  text: "text"
  target: "target"

save:
  path_to_folder: 'saved_models/'