# data
train_data_path: "data/train.csv"
test_data_path: "data/test.csv"
sep: ','
text_column: "text"
target_column: "target"

# model
seed: 42
n_jobs: -1

# save
path_to_save_folder: 'models'
save_filename: 'model.joblib'
