load_data:
  train_data:
    path: "data/data_train.csv"
    usecols: ['text', 'target']
  test_data:
    path: "data/data_test.csv"
    usecols: ['text', 'target']

select_columns:s
  text: "text"
  target: "target"

save:
  path_to_folder: 'saved_models/'